import {StyleSheet} from "react-native"
import {windowHeight, windowWidth} from "../../../shared/Const"

export const style = StyleSheet.create({
  container: {
    backgroundColor: 'transparent',
    flex: 1,
    width: '100%',
    alignItems: 'center',
  },
  loginContainer: {
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    width: '100%',
  },
  loginContent: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    width: '85%',
    height: '80%',
    bottom: 0,
    position: 'absolute',
  },
  title: {
    width: windowWidth / 2,
    fontSize: 30,
    marginBottom: 50,
    color: '#A4AEB4',
    textAlign: 'center'
  },
  background: {
    position: 'absolute',
    top: 0,
    left: -windowWidth / 2,
    bottom: 0,
    right: 0,
    width: windowWidth,
    height: windowHeight
  },
  textarea: {
    borderBottomWidth: 1,
    borderColor: 'white',
    color: 'white',
    fontSize: 16,
    paddingRight: 10,
    lineHeight: 23,
  },
  primaryBtn: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    backgroundColor: 'blue',
    borderRadius: 100,
    overflow: 'hidden',
  },
  btnText: {
    fontSize: 20,
    color: 'white',
  },
  popupContent: {
    justifyContent: 'center',
    flex: 1,
    width: '100%',
    backgroundColor: '#161827',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 10,
    paddingBottom: 50,
    paddingRight: 30,
    paddingLeft: 30,
    position: 'absolute',
    bottom: 0,
    zIndex: 20,
  },
  popupItem: {
    position: 'relative',
    width: '100%',
    flex: 1,
    textAlign: 'left',
    paddingTop: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#22242c',
  },
  greyText: {
    fontSize: 15,
    color: 'white'
  },
  more: {
    position: 'absolute',
    top: 5,
    flexDirection: 'row',
    right: 30,
    width: 25,
    height: 20,
  },
  moreDots: {
    width: 5,
    height: 5,
    backgroundColor: '#a4aeb4',
    borderRadius: 10,
    marginLeft: 2,
    marginRight: 2,
  },
  videoImage: {
    width: 100,
    height: 90,
    marginRight: 10,
  },
  videoInfo: {
    width: 100,
    height: 90,
  },
  image: {
    width: 100,
    height: 90,
  },
  duration: {
    position: 'absolute',
    bottom: 5,
    right: 10,
    zIndex: 2,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 100,
    paddingLeft: 5,
    paddingRight: 5,
    paddingTop: 3,
    paddingBottom: 3,
    alignItems: 'center',
  },
  text: {
    fontSize: 12,
    color: 'white',
  },
  name: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#dedede',
    marginBottom: 5,
    width: 100 - 80,
  },
  desc: {
    fontSize: 12,
    color: '#d1d1d1',
  },
  authorInfo: {
    flexDirection: 'row',
    marginTop: 10,
    alignItems: 'center',
  },
  profile: {
    width: 100,
    height: 20,
    borderWidth: 0.5,
    borderColor: '#5d5d67',
    borderRadius: 100,
    marginRight: 10,
  },
  author: {
    fontSize: 12,
    color: '#a4aeb4',
  },
  views: {
    fontSize: 12,
    color: '#a4aeb4',
  },
  dot: {
    width: 5,
    height: 5,
    backgroundColor: '#a4aeb4',
    borderRadius: 10,
    marginLeft: 10,
    marginRight: 10,
  },
  form: {
    alignItems: 'center',
    flex: 1,
    width: '85%',
    height: '88%',
    bottom: 0,
    position: 'absolute',
  },
  formGroup: {
    position: 'relative',
    width: '100%',
    height: 'auto',
    fontSize: 18,
    color: 'white',
  },
  input: {
    width: '100%',
    // height: 0,
    // borderBottomWidth: 1,
    // borderColor: 'white',
    // color: 'white',
    fontSize: 16,
    height: (windowHeight * 7 ) / 100,
    marginBottom: (windowHeight * 2 ) / 100,
    color: '#A4AEB4',
    borderColor: 'rgba(164, 174, 180, 0.4)',
    borderBottomWidth: 1,
  },
  focusBlured: {
    position: 'absolute',
    top: '-20%',
    left: '-10%',
    bottom: 0,
    right: 0,
    width: '120%',
    height: 'auto',
  },
  borderedBtn: {
    position: 'relative',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    backgroundColor: 'transparent',
    borderRadius: 100,
    borderWidth: 2,
    borderColor: '#888888',
    overflow: 'hidden',
    // marginBottom: 25,
    height: (windowHeight * 7 ) / 100,
    marginBottom: (windowHeight * 2 ) / 100,
  },
  errorBlured: {
    position: 'absolute',
    top: '-20%',
    left: '-10%',
    bottom: 0,
    right: 0,
    width: '120%',
    height: 'auto',
  },
  errorText: {
    position: 'absolute',
    color: '#ff0000',
    fontSize: 12,
    bottom: 0,
    right: 0,
  },
  apierrorText: {
    position: 'relative',
    color: '#ff0000',
    fontSize: 14,
    marginBottom: 10,
  },
  showPass: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    width: windowHeight / 25,
    height: windowHeight / 25,
    marginTop: 5,
  },
  socialIcons: {
    position: 'relative',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    color: '#fff',
    flexDirection: 'row',
    marginTop: windowHeight / 50,
  },
  checkedImg: {
    marginLeft: 7,
    marginRight: 7,
    width: 30,
    height: 30,
  },
})
