import {StyleSheet} from "react-native"
import {windowHeight} from "../../../shared/Const"

export const style = StyleSheet.create({
    loader: {
        position: 'absolute',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
        width: 'auto',
        height: '100%',
        zIndex: 9999,
    },
    container: {
        backgroundColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
        flex: 1,
        width: '100%',
    },
    checkedImg: {
        marginLeft: 10,
        marginRight: 10,
        width: windowHeight / 20,
        height: windowHeight / 20,
    },
    background: {
        position: 'absolute',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
        width: 'auto',
        height: '100%',
        zIndex: 9999
    },
    loginContent: {
        alignItems: 'center',
        justifyContent: 'center',
        flex: 1,
        width: '85%',
        height: '80%',
        bottom: 0,
        position: 'absolute',
    },
    formGroup: {
        position: 'relative',
        width: '100%',
        height: 'auto',
        fontSize: 18,
        color: 'white',
    },
    input: {
        width: '100%',
        // height: 0,
        // borderBottomWidth: 1,
        // borderColor: 'white',
        // color: 'white',
        fontSize: 16,
        height: (windowHeight * 7 ) / 100,
        marginBottom: (windowHeight * 2 ) / 100,
        color: '#A4AEB4',
        borderColor: 'rgba(164, 174, 180, 0.4)',
        borderBottomWidth: 1,
    },
    forgotPass: {
        position: 'relative',
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        marginBottom: 30,
    },
    link: {
        color: '#d0d0d0',
        textAlign: 'center',
        fontSize: 16,
        textDecorationLine: 'underline',
    },
    buttons: {
        position: 'relative',
        width: '100%',
        height: 'auto',
        textAlign: 'center',
    },
    primaryBtn: {
        position: 'relative',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        width: '100%',
        backgroundColor: 'blue',
        borderRadius: 100,
        overflow: 'hidden',
        height: (windowHeight * 8 ) / 100,
        marginBottom: (windowHeight * 2 ) / 100,
    },
    text: {
        fontSize: 20,
        color: 'white',
    },
    borderedBtn: {
        position: 'relative',
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        backgroundColor: 'transparent',
        borderRadius: 100,
        borderWidth: 2,
        borderColor: '#888888',
        overflow: 'hidden',
        // marginBottom: 25,
        height: (windowHeight * 7 ) / 100,
        marginBottom: (windowHeight * 2 ) / 100,
    },
    greyText: {
        color: '#888888',
        fontSize: 20,
    },
    checkbox: {
        position: 'relative',
        width: 'auto',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
    },
    notChecked: {
        borderWidth: 2,
        borderColor: '#888888',
    },
    socialText: {
        position: 'relative',
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        color: '#fff',
        fontSize: 20,
        marginTop: 20,
        marginBottom: windowHeight / 35,
    },
    socialIcons: {
        position: 'relative',
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        color: '#fff',
        flexDirection: 'row',
        marginBottom: windowHeight / 35,
    },
    terms: {
        position: 'relative',
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        marginBottom: windowHeight / 50,
    },
    termsText: {
        color: '#d0d0d0',
        fontSize: 14,
    },
    privacy: {
        position: 'relative',
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
    },
    privacyText: {
        color: '#d0d0d0',
        fontSize: 14,
    },
    focusBlured: {
        position: 'absolute',
        top: '-20%',
        left: '-10%',
        bottom: 0,
        right: 0,
        width: '120%',
        height: 'auto',
    },
    errorBlured: {
        position: 'absolute',
        top: '-20%',
        left: '-10%',
        bottom: 0,
        right: 0,
        width: '120%',
        height: 'auto',
    },
    errorText: {
        position: 'absolute',
        color: '#ff0000',
        fontSize: 12,
        bottom: 0,
        right: 0,
    },
    apierrorText: {
        position: 'relative',
        color: '#ff0000',
        fontSize: 14,
        marginBottom: 10,
    },
    showPass: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        right: 0,
        width: windowHeight / 25,
        height: windowHeight / 25,
        marginTop: 5,
    }
})
